### ISSUE TITLE
result no avaliable

### ISSUE THREAD

**Issue by Stalker-moment** [Xeukxz/get-twitter-media#3]
{
  found: true,
  type: 'Video',
  instances: [
    {
      sourceURL: '/',
      resolution: 'Back to\n\t\t\t\t\t\t\tmain page',
      width: 'Back to\n\t\t\t\t\t\t\tmain page',
      height: undefined
    }
  ]
}

**Comment by Xeukxz** [comment]
https://github.com/Xeukxz/get-twitter-media/issues/1#issuecomment-1666948110 should be fixed
